// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnb6HGzkhDymmpqJoVRCu3w1yPUXLOdRw',
    appId: '1:107361784050:web:d14d00948c9be197f5406b',
    messagingSenderId: '107361784050',
    projectId: 'learningapp-5a313',
    authDomain: 'learningapp-5a313.firebaseapp.com',
    databaseURL: 'https://learningapp-5a313-default-rtdb.firebaseio.com',
    storageBucket: 'learningapp-5a313.appspot.com',
    measurementId: 'G-5G14MD8CQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcmoVuVTZVPBhYky-XkFQmTvrXsQ7H3RM',
    appId: '1:107361784050:android:126832145ef3409cf5406b',
    messagingSenderId: '107361784050',
    projectId: 'learningapp-5a313',
    databaseURL: 'https://learningapp-5a313-default-rtdb.firebaseio.com',
    storageBucket: 'learningapp-5a313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMv0blJNp7ldpQILRhKxFB4DDMb9BZMnM',
    appId: '1:107361784050:ios:db726a35cff108caf5406b',
    messagingSenderId: '107361784050',
    projectId: 'learningapp-5a313',
    databaseURL: 'https://learningapp-5a313-default-rtdb.firebaseio.com',
    storageBucket: 'learningapp-5a313.appspot.com',
    iosBundleId: 'com.example.learningapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMv0blJNp7ldpQILRhKxFB4DDMb9BZMnM',
    appId: '1:107361784050:ios:69037f9f46bfdce6f5406b',
    messagingSenderId: '107361784050',
    projectId: 'learningapp-5a313',
    databaseURL: 'https://learningapp-5a313-default-rtdb.firebaseio.com',
    storageBucket: 'learningapp-5a313.appspot.com',
    iosBundleId: 'com.example.learningapp.RunnerTests',
  );
}
