// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvjJqoYMiPa_Tkr8WDhqSD_ptbfkZmMYY',
    appId: '1:889410134319:web:f3aa1841a15e0e0f8101da',
    messagingSenderId: '889410134319',
    projectId: 'petshopapp-72732',
    authDomain: 'petshopapp-72732.firebaseapp.com',
    databaseURL: 'https://petshopapp-72732-default-rtdb.firebaseio.com',
    storageBucket: 'petshopapp-72732.appspot.com',
    measurementId: 'G-LQ6DP5LJRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPjQmYR6jgsBsTE0SxOay5_immFxSlWao',
    appId: '1:889410134319:android:b6b0f53f1f03dfc18101da',
    messagingSenderId: '889410134319',
    projectId: 'petshopapp-72732',
    databaseURL: 'https://petshopapp-72732-default-rtdb.firebaseio.com',
    storageBucket: 'petshopapp-72732.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOvDYdk1481z41Zk-T4p6WSDEAQgskFQs',
    appId: '1:889410134319:ios:10dca9643a166d5e8101da',
    messagingSenderId: '889410134319',
    projectId: 'petshopapp-72732',
    databaseURL: 'https://petshopapp-72732-default-rtdb.firebaseio.com',
    storageBucket: 'petshopapp-72732.appspot.com',
    androidClientId: '889410134319-mo8hmpnkgv1isadjsev9ieers2gd25uj.apps.googleusercontent.com',
    iosClientId: '889410134319-gl2qjisdra4fm1umjun01e4aiml3lkbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.petshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOvDYdk1481z41Zk-T4p6WSDEAQgskFQs',
    appId: '1:889410134319:ios:10dca9643a166d5e8101da',
    messagingSenderId: '889410134319',
    projectId: 'petshopapp-72732',
    databaseURL: 'https://petshopapp-72732-default-rtdb.firebaseio.com',
    storageBucket: 'petshopapp-72732.appspot.com',
    androidClientId: '889410134319-mo8hmpnkgv1isadjsev9ieers2gd25uj.apps.googleusercontent.com',
    iosClientId: '889410134319-gl2qjisdra4fm1umjun01e4aiml3lkbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.petshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvjJqoYMiPa_Tkr8WDhqSD_ptbfkZmMYY',
    appId: '1:889410134319:web:d5e4f6ab9faf93858101da',
    messagingSenderId: '889410134319',
    projectId: 'petshopapp-72732',
    authDomain: 'petshopapp-72732.firebaseapp.com',
    databaseURL: 'https://petshopapp-72732-default-rtdb.firebaseio.com',
    storageBucket: 'petshopapp-72732.appspot.com',
    measurementId: 'G-DB5PVD74EJ',
  );
}
